[package]
name = "src"
version = "1.0.1"
cairo-version = "2.7.0"

[tool.NodeGuardians]
part_1 = "Hawk Spirit"
part_2 = "Hawk Spirit Trait"
part_3 = "Wind Spirit"

[dependencies]
cairo_test = "2.7.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest