[package]
name = "src"
version = "0.1.1"
cairo-version = "2.0.0"

[tool.NodeGuardians]
part_3 = "Hello Guardian"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest