[package]
name = "src"
version = "1.3.0"
cairo-version = "2.7.0"

[dependencies]
cairo_test = "2.7.0"

[tool.NodeGuardians]
part_3 = "Hello Guardian"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest