[package]
name = "src"
version = "1.3.0"
cairo-version = "2.5.3"

[tool.NodeGuardians]
part_3 = "Hello Guardian"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest