[package]
name = "skirmishing_scarabs"
version = "0.1.0"

[scripts]
test = "cairo-test ."

[tool.NodeGuardians]
part_1 = "Simple Skirmishes"
part_2 = "Talent Mechanic"
part_3 = "Team Battle"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest