[package]
name = "racing_riverboats"
version = "0.1.0"

[scripts]
test = "cairo-test ."

[tool.NodeGuardians]
part_1 = "Find Crocodiles"
part_2 = "Sail River"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest