[package]
name = "src"
version = "0.1.0"
cairo-version = "1.1.0"

[tool.NodeGuardians]
part_1 = "Find Crocodiles"
part_2 = "Sail River"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest