[package]
name = "src"
version = "1.0.0"
cairo-version = "2.7.0"

[dependencies]
starknet = "2.7.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.27.0" }

[[target.starknet-contract]]
casm = true

[scripts]
test = "snforge test"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest