[package]
name = "src"
version = "0.1.0"

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental_v0.1.0"

[dependencies]
starknet = ">=1.0.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest